### ISSUE TITLE
How to set up RivTable

### ISSUE THREAD

**Issue by ARBoyGo** [loooltooot/rivia#2]
It just showing seed. 
Give some guidance please. 

**Edit**
Found it 
Just give random seed
It'll generates code accordingly. 
Good features.

**Comment by loooltooot** [comment]
Hello! Yes, it's pretty easy, just tap the button "new RivTable" and give it a random value: word, numbers, any symbol (except emojies 😉) and etc. It will automatically shuffle the table in unique way

**Comment by ARBoyGo** [comment]
Great app mate, Still I didn't get a uses of this app. Except lovers, Agents, Some confidential information, Etc.. has use of this all, Can you mention a feature of this app for common people ( If you don't mind ).

**Comment by loooltooot** [comment]
> Can you mention a feature of this app for common people.

Sorry for long answering, mate. You literally mention all features of this app. But the one – security and privacy of your messages. Most of the messengers sell data to the third party people, and if you have encrypted messages they can't get any sense of its meaning

**Comment by ARBoyGo** [comment]
Thanks... Closing it after long period lol
